# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Order Display APP"
client_id = "4dd78f1277adcc324aeebbe0fa90f175"
application_url = "https://history-broad-perl-switch.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_all_orders"

[auth]
redirect_urls = [
  "https://history-broad-perl-switch.trycloudflare.com/auth/callback",
  "https://history-broad-perl-switch.trycloudflare.com/auth/shopify/callback",
  "https://history-broad-perl-switch.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wearbar.myshopify.com"
